### ISSUE TITLE
Springboot 1.2.3.RELEASE integration

### ISSUE THREAD

**Issue by lrkwz** [la-team/lightadmin-springboot#5]
I'm unsucessfully trying to integrate in a sb 1.2.3.RELEASE spring.io generated app.
App il started in a simple startup class

    @SpringBootApplication
    public class MyApplication {
	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
    }

I've called LA configure() in

    @Configuration
    @EnableAutoConfiguration
    public class LightAdminConfigurator {
	@Bean
	public ServletContextInitializer initializer() {
		return new ServletContextInitializer() {
			@Override
			public void onStartup(ServletContext servletContext) throws ServletException {
      ...

or in:

    public class LightAdminConfigurator implements WebApplicationInitializer {
        @Override
        public void onStartup(ServletContext servletContext) throws ServletException {

but "/admin" is not mapped in either case.

**Comment by lazaridis-com** [comment]
I can confirm problems when changing the `1.1.6.RELEASE` versionof this project to the 1.2.3.RELEASE. It seems ligthadmin does not support the latest SB release.

**Comment by lazaridis-com** [comment]
similar error within la-team/light-admin#153

**Comment by lazaridis-com** [comment]
try with latest master

https://github.com/la-team/light-admin/commit/13f255a08f337b5c4c040bfc18d95cd94a923c96

should work now (with spring-boot-1.2.3) - use the lightadmin-boot code contained there.

**Comment by max-dev** [comment]
Hi @lrkwz , LightAdmin (1.2.0.BUILD-SNAPSHOT) has been upgraded to use Spring Boot 1.2.3.
Can you check your issue is fixed now, please?

**Comment by jordanjennings** [comment]
@max-dev It doesn't look like the snapshot repository is reflecting the change yet:

http://lightadmin.org/nexus/content/repositories/snapshots/org/lightadmin/lightadmin/1.2.0.BUILD-SNAPSHOT/

When will it be available?

**Comment by max-dev** [comment]
@jordanjennings Not sure, what's wrong, but I've republished version anyway:
 - https://oss.sonatype.org/content/repositories/snapshots/org/lightadmin/lightadmin/1.2.0.BUILD-SNAPSHOT/
 - http://lightadmin.org/nexus/content/repositories/snapshots/org/lightadmin/lightadmin/1.2.0.BUILD-SNAPSHOT/

Can you check, please?

**Comment by jordanjennings** [comment]
@max-dev Thanks, that seems to have cleared it up! Previously it was throwing a  NoClassDefFoundException based on a class that was moved in spring boot 1.2.3 (can't remember the class name now).

**Comment by max-dev** [comment]
Great!
